"""9~11단계: 커밋 → 푸시 → E2E → 백로그 등록.

바깥으로 나가는 유일한 액션은 push다. 기본 게이트가 manual인 이유.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

from factory.context import Ctx, prompt
from factory.models import Status, Ticket, TicketType
from factory.worker.base import WorkerTask


def git(ctx: Ctx, *args: str, check: bool = False) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args], cwd=str(ctx.cfg.repo), capture_output=True, text=True,
        encoding="utf-8", errors="replace", check=check, timeout=120,
    )


def has_changes(ctx: Ctx) -> bool:
    return bool(git(ctx, "status", "--porcelain").stdout.strip())


def ensure_identity(ctx: Ctx) -> None:
    """저장소에 커밋 신원이 없으면 로컬 신원을 심는다.

    전역 git config가 비어 있는 CI/컨테이너에서 커밋이 조용히 실패하는 것을 막는다.
    저장소 로컬 설정이므로 사용자의 전역 설정은 건드리지 않는다.
    """
    for key, val in (("user.name", "sw-factory"), ("user.email", "sw-factory@localhost")):
        if not git(ctx, "config", "--get", key).stdout.strip():
            git(ctx, "config", key, val)
            ctx.log(f"  git {key} 미설정 -> 저장소 로컬로 '{val}' 지정")


def commit(ctx: Ctx, ticket: Ticket) -> str | None:
    """티켓 단위 커밋. 커밋 메시지가 코드↔티켓↔FSM 추적성의 마지막 고리다."""
    if not has_changes(ctx):
        ctx.log(f"  {ticket.key}: 변경 없음 → 커밋 생략")
        return None

    ensure_identity(ctx)
    git(ctx, "add", "-A")
    subject = f"{ticket.key} {ticket.title}"[:72]
    # 트레일러는 반드시 마지막 문단이어야 한다. 뒤에 다른 줄이 붙으면 git이 트레일러로
    # 인식하지 않아 `git log --format=%(trailers:key=FSM-Transition)` 로 뽑을 수 없다.
    body = "\n".join([
        "Generated by sw_factory.",
        "",
        f"FSM-Transition: {ticket.fsm_ref}",
        f"Use-Case: {ticket.usecase_ref}",
        f"Spec-Signature: {ticket.signature}",
        f"DoD: {', '.join(ticket.dod_tests)}",
    ])
    res = git(ctx, "commit", "-m", subject, "-m", body)
    if res.returncode != 0:
        ctx.log(f"  커밋 실패: {res.stderr.strip()[:300]}")
        return None
    sha = git(ctx, "rev-parse", "--short", "HEAD").stdout.strip()
    ctx.log(f"  커밋 {sha}: {subject}")
    ctx.tracker.comment(ticket.key, f"commit {sha}: {subject}")
    return sha


def push(ctx: Ctx, remote: str = "origin", branch: str | None = None) -> bool:
    branch = branch or git(ctx, "rev-parse", "--abbrev-ref", "HEAD").stdout.strip()
    res = git(ctx, "push", remote, branch)
    ok = res.returncode == 0
    ctx.log(f"  push {remote}/{branch}: {'성공' if ok else 'FAIL ' + res.stderr.strip()[:200]}")
    return ok


# --------------------------------------------------------------------------
# E2E
# --------------------------------------------------------------------------

def run_e2e(ctx: Ctx):
    """e2e 스위트 실행. tests/e2e 가 없으면 건너뛴다(없는 걸 실패로 치지 않는다)."""
    from factory.stages.build import TestOutcome, run_tests

    e2e_dir = ctx.cfg.repo / "tests" / "e2e"
    if not e2e_dir.exists() or not any(e2e_dir.rglob("test_*.py")):
        return None
    return run_tests(ctx, nodes=["tests/e2e"])


def debug_e2e(ctx: Ctx, outcome) -> bool:
    from factory.stages.build import IMPL_TOOLS, SPEC_CONFLICT, restore_if_tampered, snapshot_tests

    before = snapshot_tests(ctx)
    saved = {rel: (ctx.cfg.repo / rel).read_bytes() for rel in before}
    log = git(ctx, "log", "--oneline", "-8").stdout

    res = ctx.worker.run(WorkerTask(
        prompt=prompt("debug_e2e", output=outcome.output, recent_commits=log),
        cwd=ctx.cfg.repo,
        allowed_tools=IMPL_TOOLS,
        timeout=ctx.cfg.limits.worker_timeout_s,
        label="debug_e2e",
    ))
    v = restore_if_tampered(ctx, before, saved)
    if v:
        ctx.log(f"  ⚠ E2E 디버그 중 테스트 무단 수정 → 되돌림: {', '.join(v)}")
    return res.ok and SPEC_CONFLICT not in res.text


# --------------------------------------------------------------------------
# 백로그 등록 — 루프가 발산하지 않게 하는 안전장치
# --------------------------------------------------------------------------

def raise_bug(ctx: Ctx, origin: Ticket, reason: str, evidence: str = "") -> Ticket:
    """자동으로 못 끝낸 것을 사람 검토 큐로 넘긴다.

    이게 없으면 루프는 같은 티켓에서 영원히 재시도하거나, 조용히 실패를 삼킨다.
    """
    bug = ctx.tracker.create(Ticket(
        type=TicketType.BUG.value,
        title=f"[자동] {origin.key} 실패: {reason[:60]}",
        description="\n".join([
            f"원인 티켓: {origin.key} — {origin.title}",
            f"FSM 전이: {origin.fsm_ref}",
            f"시도 횟수: {origin.attempts}",
            f"사유: {reason}",
            "",
            "```",
            evidence[-3000:],
            "```",
        ]),
        parent=origin.parent,
        fsm_ref=origin.fsm_ref,
        usecase_ref=origin.usecase_ref,
        labels=["auto", "needs-human"],
        dod_tests=list(origin.dod_tests),
    ))
    origin.status = Status.BLOCKED.value
    origin.last_error = reason
    ctx.tracker.update(origin)
    ctx.tracker.comment(origin.key, f"자동 처리 한계 도달 → {bug.key} 로 승격, BLOCKED 처리")
    ctx.log(f"  ⛔ {origin.key} BLOCKED → 백로그 {bug.key} 등록 ({reason[:80]})")
    return bug
